// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAxu1xtzDPenNcveUfTnjiVrZHQM-iK1I',
    appId: '1:221289023080:web:b2db69e736e067ad3d5ddd',
    messagingSenderId: '221289023080',
    projectId: 'loginapp-4bc89',
    authDomain: 'loginapp-4bc89.firebaseapp.com',
    storageBucket: 'loginapp-4bc89.firebasestorage.app',
    measurementId: 'G-1SGY9HFV75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjXxKyfQzQzy-chEGldH3ajlWYcEX0p4o',
    appId: '1:221289023080:android:fcde3e27f9a6c9cb3d5ddd',
    messagingSenderId: '221289023080',
    projectId: 'loginapp-4bc89',
    storageBucket: 'loginapp-4bc89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT8Dn3czDNIzJ1BAnmnX69y_l7n1oTtZ4',
    appId: '1:221289023080:ios:b973231ca6c0797c3d5ddd',
    messagingSenderId: '221289023080',
    projectId: 'loginapp-4bc89',
    storageBucket: 'loginapp-4bc89.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT8Dn3czDNIzJ1BAnmnX69y_l7n1oTtZ4',
    appId: '1:221289023080:ios:b973231ca6c0797c3d5ddd',
    messagingSenderId: '221289023080',
    projectId: 'loginapp-4bc89',
    storageBucket: 'loginapp-4bc89.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAxu1xtzDPenNcveUfTnjiVrZHQM-iK1I',
    appId: '1:221289023080:web:3af6bce92c1196433d5ddd',
    messagingSenderId: '221289023080',
    projectId: 'loginapp-4bc89',
    authDomain: 'loginapp-4bc89.firebaseapp.com',
    storageBucket: 'loginapp-4bc89.firebasestorage.app',
    measurementId: 'G-222BDXPDXD',
  );
}
